receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'clara-discord'
          scrape_interval: 60s
          static_configs:
            - targets: ['${METRICS_TARGET}']

processors:
  batch:
    timeout: 10s

exporters:
  prometheusremotewrite:
    endpoint: ${PROMETHEUS_REMOTE_WRITE_URL}
    auth:
      authenticator: basicauth/metrics

extensions:
  basicauth/metrics:
    client_auth:
      username: ${PROMETHEUS_USERNAME}
      password: ${PROMETHEUS_PASSWORD}

service:
  extensions: [basicauth/metrics]
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [prometheusremotewrite]
