receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'clara-discord'
          scrape_interval: 60s
          static_configs:
            - targets: ['${env:METRICS_TARGET}']

processors:
  batch:
    timeout: 10s

exporters:
  otlphttp:
    endpoint: ${env:OTEL_EXPORTER_OTLP_ENDPOINT}
    headers:
      Authorization: ${env:OTEL_EXPORTER_OTLP_AUTH}

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [otlphttp]
